create table administrador (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente (id bigint not null auto_increment, apellidos varchar(255), direccion varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table envio (id bigint not null auto_increment, destino varchar(255), empresa_reparto varchar(255), fecha_entrega date, fecha_modificacion date, origen varchar(255), administrador_id bigint, cliente_id bigint, estado_id bigint, repartidor_id bigint, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, estado varchar(255), primary key (id)) engine=InnoDB;
create table repartidor (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), fecha_hora_actualizacion datetime, latitud float(53) not null, longitud float(53) not null, nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
alter table envio add constraint FKbih5sppcmrmt5seal0use7hoe foreign key (administrador_id) references administrador (id);
alter table envio add constraint FKm6gm0b7inxpeduuydypyx59ih foreign key (cliente_id) references cliente (id);
alter table envio add constraint FKf9f0abk7mrbmyclwkff1smux0 foreign key (estado_id) references estado (id);
alter table envio add constraint FKt3622sjou1h86jericj5wx6a8 foreign key (repartidor_id) references repartidor (id);
create table administrador (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente (id bigint not null auto_increment, apellidos varchar(255), direccion varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table envio (id bigint not null auto_increment, destino varchar(255), empresa_reparto varchar(255), fecha_entrega date, fecha_modificacion date, origen varchar(255), administrador_id bigint, cliente_id bigint, estado_id bigint, repartidor_id bigint, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, estado varchar(255), primary key (id)) engine=InnoDB;
create table repartidor (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), fecha_hora_actualizacion datetime, latitud float(53) not null, longitud float(53) not null, nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
alter table envio add constraint FKbih5sppcmrmt5seal0use7hoe foreign key (administrador_id) references administrador (id);
alter table envio add constraint FKm6gm0b7inxpeduuydypyx59ih foreign key (cliente_id) references cliente (id);
alter table envio add constraint FKf9f0abk7mrbmyclwkff1smux0 foreign key (estado_id) references estado (id);
alter table envio add constraint FKt3622sjou1h86jericj5wx6a8 foreign key (repartidor_id) references repartidor (id);
create table administrador (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente (id bigint not null auto_increment, apellidos varchar(255), direccion varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table envio (id bigint not null auto_increment, destino varchar(255), empresa_reparto varchar(255), fecha_entrega date, fecha_modificacion date, origen varchar(255), administrador_id bigint, cliente_id bigint, estado_id bigint, repartidor_id bigint, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, estado varchar(255), primary key (id)) engine=InnoDB;
create table repartidor (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), fecha_hora_actualizacion datetime, latitud float(53) not null, longitud float(53) not null, nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
alter table envio add constraint FKbih5sppcmrmt5seal0use7hoe foreign key (administrador_id) references administrador (id);
alter table envio add constraint FKm6gm0b7inxpeduuydypyx59ih foreign key (cliente_id) references cliente (id);
alter table envio add constraint FKf9f0abk7mrbmyclwkff1smux0 foreign key (estado_id) references estado (id);
alter table envio add constraint FKt3622sjou1h86jericj5wx6a8 foreign key (repartidor_id) references repartidor (id);
create table administrador (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente (id bigint not null auto_increment, apellidos varchar(255), direccion varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table envio (id bigint not null auto_increment, destino varchar(255), empresa_reparto varchar(255), fecha_entrega date, fecha_modificacion date, origen varchar(255), administrador_id bigint, cliente_id bigint, estado_id bigint, repartidor_id bigint, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, estado varchar(255), primary key (id)) engine=InnoDB;
create table repartidor (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), fecha_hora_actualizacion datetime, latitud float(53) not null, longitud float(53) not null, nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
alter table envio add constraint FKbih5sppcmrmt5seal0use7hoe foreign key (administrador_id) references administrador (id);
alter table envio add constraint FKm6gm0b7inxpeduuydypyx59ih foreign key (cliente_id) references cliente (id);
alter table envio add constraint FKf9f0abk7mrbmyclwkff1smux0 foreign key (estado_id) references estado (id);
alter table envio add constraint FKt3622sjou1h86jericj5wx6a8 foreign key (repartidor_id) references repartidor (id);
create table administrador (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente (id bigint not null auto_increment, apellidos varchar(255), direccion varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table envio (id bigint not null auto_increment, destino varchar(255), empresa_reparto varchar(255), fecha_entrega date, fecha_modificacion date, origen varchar(255), administrador_id bigint, cliente_id bigint, estado_id bigint, repartidor_id bigint, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, estado varchar(255), primary key (id)) engine=InnoDB;
create table repartidor (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), fecha_hora_actualizacion datetime, latitud float(53) not null, longitud float(53) not null, nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
alter table envio add constraint FKbih5sppcmrmt5seal0use7hoe foreign key (administrador_id) references administrador (id);
alter table envio add constraint FKm6gm0b7inxpeduuydypyx59ih foreign key (cliente_id) references cliente (id);
alter table envio add constraint FKf9f0abk7mrbmyclwkff1smux0 foreign key (estado_id) references estado (id);
alter table envio add constraint FKt3622sjou1h86jericj5wx6a8 foreign key (repartidor_id) references repartidor (id);
create table administrador (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente (id bigint not null auto_increment, apellidos varchar(255), direccion varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table envio (id bigint not null auto_increment, destino varchar(255), empresa_reparto varchar(255), fecha_entrega date, fecha_modificacion date, origen varchar(255), administrador_id bigint, cliente_id bigint, estado_id bigint, repartidor_id bigint, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, estado varchar(255), primary key (id)) engine=InnoDB;
create table repartidor (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), fecha_hora_actualizacion datetime, latitud float(53) not null, longitud float(53) not null, nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
alter table envio add constraint FKbih5sppcmrmt5seal0use7hoe foreign key (administrador_id) references administrador (id);
alter table envio add constraint FKm6gm0b7inxpeduuydypyx59ih foreign key (cliente_id) references cliente (id);
alter table envio add constraint FKf9f0abk7mrbmyclwkff1smux0 foreign key (estado_id) references estado (id);
alter table envio add constraint FKt3622sjou1h86jericj5wx6a8 foreign key (repartidor_id) references repartidor (id);
create table administrador (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente (id bigint not null auto_increment, apellidos varchar(255), direccion varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table envio (id bigint not null auto_increment, destino varchar(255), empresa_reparto varchar(255), fecha_entrega date, fecha_modificacion date, origen varchar(255), administrador_id bigint, cliente_id bigint, estado_id bigint, repartidor_id bigint, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, estado varchar(255), primary key (id)) engine=InnoDB;
create table repartidor (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), fecha_hora_actualizacion datetime, latitud float(53) not null, longitud float(53) not null, nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
alter table envio add constraint FKbih5sppcmrmt5seal0use7hoe foreign key (administrador_id) references administrador (id);
alter table envio add constraint FKm6gm0b7inxpeduuydypyx59ih foreign key (cliente_id) references cliente (id);
alter table envio add constraint FKf9f0abk7mrbmyclwkff1smux0 foreign key (estado_id) references estado (id);
alter table envio add constraint FKt3622sjou1h86jericj5wx6a8 foreign key (repartidor_id) references repartidor (id);
create table administrador (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente (id bigint not null auto_increment, apellidos varchar(255), direccion varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table envio (id bigint not null auto_increment, destino varchar(255), empresa_reparto varchar(255), fecha_entrega date, fecha_modificacion date, origen varchar(255), administrador_id bigint, cliente_id bigint, estado_id bigint, repartidor_id bigint, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, estado varchar(255), primary key (id)) engine=InnoDB;
create table repartidor (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), fecha_hora_actualizacion datetime, latitud float(53) not null, longitud float(53) not null, nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
alter table envio add constraint FKbih5sppcmrmt5seal0use7hoe foreign key (administrador_id) references administrador (id);
alter table envio add constraint FKm6gm0b7inxpeduuydypyx59ih foreign key (cliente_id) references cliente (id);
alter table envio add constraint FKf9f0abk7mrbmyclwkff1smux0 foreign key (estado_id) references estado (id);
alter table envio add constraint FKt3622sjou1h86jericj5wx6a8 foreign key (repartidor_id) references repartidor (id);
create table administrador (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente (id bigint not null auto_increment, apellidos varchar(255), direccion varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table envio (id bigint not null auto_increment, destino varchar(255), empresa_reparto varchar(255), fecha_entrega date, fecha_modificacion date, origen varchar(255), administrador_id bigint, cliente_id bigint, estado_id bigint, repartidor_id bigint, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, estado varchar(255), primary key (id)) engine=InnoDB;
create table repartidor (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), fecha_hora_actualizacion datetime, latitud float(53) not null, longitud float(53) not null, nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
alter table envio add constraint FKbih5sppcmrmt5seal0use7hoe foreign key (administrador_id) references administrador (id);
alter table envio add constraint FKm6gm0b7inxpeduuydypyx59ih foreign key (cliente_id) references cliente (id);
alter table envio add constraint FKf9f0abk7mrbmyclwkff1smux0 foreign key (estado_id) references estado (id);
alter table envio add constraint FKt3622sjou1h86jericj5wx6a8 foreign key (repartidor_id) references repartidor (id);
create table administrador (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente (id bigint not null auto_increment, apellidos varchar(255), direccion varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table envio (id bigint not null auto_increment, destino varchar(255), empresa_reparto varchar(255), fecha_entrega date, fecha_modificacion date, origen varchar(255), administrador_id bigint, cliente_id bigint, estado_id bigint, repartidor_id bigint, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, estado varchar(255), primary key (id)) engine=InnoDB;
create table repartidor (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), fecha_hora_actualizacion datetime, latitud float(53) not null, longitud float(53) not null, nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
alter table envio add constraint FKbih5sppcmrmt5seal0use7hoe foreign key (administrador_id) references administrador (id);
alter table envio add constraint FKm6gm0b7inxpeduuydypyx59ih foreign key (cliente_id) references cliente (id);
alter table envio add constraint FKf9f0abk7mrbmyclwkff1smux0 foreign key (estado_id) references estado (id);
alter table envio add constraint FKt3622sjou1h86jericj5wx6a8 foreign key (repartidor_id) references repartidor (id);
create table administrador (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente (id bigint not null auto_increment, apellidos varchar(255), direccion varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table envio (id bigint not null auto_increment, destino varchar(255), empresa_reparto varchar(255), fecha_entrega date, fecha_modificacion date, origen varchar(255), administrador_id bigint, cliente_id bigint, estado_id bigint, repartidor_id bigint, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, estado varchar(255), primary key (id)) engine=InnoDB;
create table repartidor (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), fecha_hora_actualizacion datetime, latitud float(53) not null, longitud float(53) not null, nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
alter table envio add constraint FKbih5sppcmrmt5seal0use7hoe foreign key (administrador_id) references administrador (id);
alter table envio add constraint FKm6gm0b7inxpeduuydypyx59ih foreign key (cliente_id) references cliente (id);
alter table envio add constraint FKf9f0abk7mrbmyclwkff1smux0 foreign key (estado_id) references estado (id);
alter table envio add constraint FKt3622sjou1h86jericj5wx6a8 foreign key (repartidor_id) references repartidor (id);
create table administrador (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente (id bigint not null auto_increment, apellidos varchar(255), direccion varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table envio (id bigint not null auto_increment, destino varchar(255), empresa_reparto varchar(255), fecha_entrega date, fecha_modificacion date, origen varchar(255), administrador_id bigint, cliente_id bigint, estado_id bigint, repartidor_id bigint, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, estado varchar(255), primary key (id)) engine=InnoDB;
create table repartidor (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), fecha_hora_actualizacion datetime, latitud float(53) not null, longitud float(53) not null, nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
alter table envio add constraint FKbih5sppcmrmt5seal0use7hoe foreign key (administrador_id) references administrador (id);
alter table envio add constraint FKm6gm0b7inxpeduuydypyx59ih foreign key (cliente_id) references cliente (id);
alter table envio add constraint FKf9f0abk7mrbmyclwkff1smux0 foreign key (estado_id) references estado (id);
alter table envio add constraint FKt3622sjou1h86jericj5wx6a8 foreign key (repartidor_id) references repartidor (id);
create table administrador (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente (id bigint not null auto_increment, apellidos varchar(255), direccion varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table envio (id bigint not null auto_increment, destino varchar(255), empresa_reparto varchar(255), fecha_entrega date, fecha_modificacion date, origen varchar(255), administrador_id bigint, cliente_id bigint, estado_id bigint, repartidor_id bigint, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, estado varchar(255), primary key (id)) engine=InnoDB;
create table repartidor (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), fecha_actualizacion datetime, latitud float(53), longitud float(53), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
alter table envio add constraint FKbih5sppcmrmt5seal0use7hoe foreign key (administrador_id) references administrador (id);
alter table envio add constraint FKm6gm0b7inxpeduuydypyx59ih foreign key (cliente_id) references cliente (id);
alter table envio add constraint FKf9f0abk7mrbmyclwkff1smux0 foreign key (estado_id) references estado (id);
alter table envio add constraint FKt3622sjou1h86jericj5wx6a8 foreign key (repartidor_id) references repartidor (id);
create table administrador (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente (id bigint not null auto_increment, apellidos varchar(255), direccion varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table envio (id bigint not null auto_increment, destino varchar(255), empresa_reparto varchar(255), fecha_entrega date, fecha_modificacion date, origen varchar(255), administrador_id bigint, cliente_id bigint, estado_id bigint, repartidor_id bigint, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, estado varchar(255), primary key (id)) engine=InnoDB;
create table repartidor (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), fecha_actualizacion datetime, latitud float(53), longitud float(53), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
alter table envio add constraint FKbih5sppcmrmt5seal0use7hoe foreign key (administrador_id) references administrador (id);
alter table envio add constraint FKm6gm0b7inxpeduuydypyx59ih foreign key (cliente_id) references cliente (id);
alter table envio add constraint FKf9f0abk7mrbmyclwkff1smux0 foreign key (estado_id) references estado (id);
alter table envio add constraint FKt3622sjou1h86jericj5wx6a8 foreign key (repartidor_id) references repartidor (id);
create table administrador (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente (id bigint not null auto_increment, apellidos varchar(255), direccion varchar(255), dni varchar(255), email varchar(255), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table envio (id bigint not null auto_increment, destino varchar(255), empresa_reparto varchar(255), fecha_entrega date, fecha_modificacion date, origen varchar(255), administrador_id bigint, cliente_id bigint, estado_id bigint, repartidor_id bigint, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, estado varchar(255), primary key (id)) engine=InnoDB;
create table repartidor (id bigint not null auto_increment, apellidos varchar(255), dni varchar(255), email varchar(255), fecha_actualizacion datetime, latitud float(53), longitud float(53), nombre varchar(255), password varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
alter table envio add constraint FKbih5sppcmrmt5seal0use7hoe foreign key (administrador_id) references administrador (id);
alter table envio add constraint FKm6gm0b7inxpeduuydypyx59ih foreign key (cliente_id) references cliente (id);
alter table envio add constraint FKf9f0abk7mrbmyclwkff1smux0 foreign key (estado_id) references estado (id);
alter table envio add constraint FKt3622sjou1h86jericj5wx6a8 foreign key (repartidor_id) references repartidor (id);
